baseurl = "https://www.sripathyfication.github.io/"
title = "MEKW"
author = "Sripathy Ramaswamy"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "My Experiments With Knuth"

[[menu.main]]
    name = "About"
    url  = "https://github.com/sripathyfication/bugfree-octo-dangerzone/notes/my_exp_with_knuth/public/about.md"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"

